package gr.questweaver.core.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF67548E)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFEADDFF)
internal val onPrimaryContainerLight = Color(0xFF4F3D74)
internal val secondaryLight = Color(0xFF7C4E7E)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFFD6FC)
internal val onSecondaryContainerLight = Color(0xFF623765)
internal val tertiaryLight = Color(0xFF216A4D)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFA9F2CC)
internal val onTertiaryContainerLight = Color(0xFF005137)
internal val errorLight = Color(0xFF904A43)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF73332E)
internal val backgroundLight = Color(0xFFFEF7FF)
internal val onBackgroundLight = Color(0xFF1D1B20)
internal val surfaceLight = Color(0xFFF5FAFB)
internal val onSurfaceLight = Color(0xFF171D1E)
internal val surfaceVariantLight = Color(0xFFDDE3EA)
internal val onSurfaceVariantLight = Color(0xFF41484D)
internal val outlineLight = Color(0xFF71787E)
internal val outlineVariantLight = Color(0xFFC1C7CD)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2B3133)
internal val inverseOnSurfaceLight = Color(0xFFECF2F3)
internal val inversePrimaryLight = Color(0xFFD2BCFD)
internal val surfaceDimLight = Color(0xFFD5DBDC)
internal val surfaceBrightLight = Color(0xFFF5FAFB)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFEFF5F6)
internal val surfaceContainerLight = Color(0xFFE9EFF0)
internal val surfaceContainerHighLight = Color(0xFFE3E9EA)
internal val surfaceContainerHighestLight = Color(0xFFDEE3E5)

internal val primaryDark = Color(0xFFD2BCFD)
internal val onPrimaryDark = Color(0xFF38265C)
internal val primaryContainerDark = Color(0xFF4F3D74)
internal val onPrimaryContainerDark = Color(0xFFEADDFF)
internal val secondaryDark = Color(0xFFECB4EC)
internal val onSecondaryDark = Color(0xFF49204D)
internal val secondaryContainerDark = Color(0xFF623765)
internal val onSecondaryContainerDark = Color(0xFFFFD6FC)
internal val tertiaryDark = Color(0xFF8ED5B1)
internal val onTertiaryDark = Color(0xFF003825)
internal val tertiaryContainerDark = Color(0xFF005137)
internal val onTertiaryContainerDark = Color(0xFFA9F2CC)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF561E19)
internal val errorContainerDark = Color(0xFF73332E)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF151218)
internal val onBackgroundDark = Color(0xFFE7E0E8)
internal val surfaceDark = Color(0xFF0E1415)
internal val onSurfaceDark = Color(0xFFDEE3E5)
internal val surfaceVariantDark = Color(0xFF41484D)
internal val onSurfaceVariantDark = Color(0xFFC1C7CD)
internal val outlineDark = Color(0xFF8B9297)
internal val outlineVariantDark = Color(0xFF41484D)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDEE3E5)
internal val inverseOnSurfaceDark = Color(0xFF2B3133)
internal val inversePrimaryDark = Color(0xFF67548E)
internal val surfaceDimDark = Color(0xFF0E1415)
internal val surfaceBrightDark = Color(0xFF343A3B)
internal val surfaceContainerLowestDark = Color(0xFF090F10)
internal val surfaceContainerLowDark = Color(0xFF171D1E)
internal val surfaceContainerDark = Color(0xFF1B2122)
internal val surfaceContainerHighDark = Color(0xFF252B2C)
internal val surfaceContainerHighestDark = Color(0xFF303637)

internal val lightScheme =
    lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

internal val darkScheme =
    darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
