package gr.questweaver.core.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF6750A4)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFEADDFF)
internal val onPrimaryContainerLight = Color(0xFF21005D)
internal val secondaryLight = Color(0xFF9C6E00) // Mystical Gold
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFDD663) // Derived approximate
internal val onSecondaryContainerLight = Color(0xFF1D192B) // Keep dark for now

internal val tertiaryLight = Color(0xFF0D47A1)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFD3E3FD)
internal val onTertiaryContainerLight = Color(0xFF001C3B)
internal val errorLight = Color(0xFFB3261E)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFF9DEDC)
internal val onErrorContainerLight = Color(0xFF410E0B)
internal val backgroundLight = Color(0xFFFFFBFE)
internal val onBackgroundLight = Color(0xFF1C1B1F)
internal val surfaceLight = Color(0xFFE7E0EC)
internal val onSurfaceLight = Color(0xFF1C1B1F)
internal val surfaceVariantLight = Color(0xFFE7E0EC)
internal val onSurfaceVariantLight = Color(0xFF49454F)
internal val outlineLight = Color(0xFF79747E)
internal val outlineVariantLight = Color(0xFFCAC4D0)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF313033)
internal val inverseOnSurfaceLight = Color(0xFFF4EFF4)
internal val inversePrimaryLight = Color(0xFFD0BCFF)
internal val surfaceDimLight = Color(0xFFDED8E1)
internal val surfaceBrightLight = Color(0xFFFEF7FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF7F2FA)
internal val surfaceContainerLight = Color(0xFFF3EDF7)
internal val surfaceContainerHighLight = Color(0xFFECE6F0)
internal val surfaceContainerHighestLight = Color(0xFFE6E0E9)

internal val primaryDark = Color(0xFFD0BCFF)
internal val onPrimaryDark = Color(0xFF381E72)
internal val primaryContainerDark = Color(0xFF4F378B)
internal val onPrimaryContainerDark = Color(0xFFEADDFF)
internal val secondaryDark = Color(0xFFFFD740) // Mystical Gold
internal val onSecondaryDark = Color(0xFF4A4458) // Darker contrast
internal val secondaryContainerDark = Color(0xFF8B7700) // Darker gold container
internal val onSecondaryContainerDark = Color(0xFFFDD663)
internal val tertiaryDark = Color(0xFF82B1FF)
internal val onTertiaryDark = Color(0xFF002B75)
internal val tertiaryContainerDark = Color(0xFF0041AC)
internal val onTertiaryContainerDark = Color(0xFFD3E3FD)
internal val errorDark = Color(0xFFF2B8B5)
internal val onErrorDark = Color(0xFF601410)
internal val errorContainerDark = Color(0xFF8C1D18)
internal val onErrorContainerDark = Color(0xFFF9DEDC)
internal val backgroundDark = Color(0xFF1C1B1F)
internal val onBackgroundDark = Color(0xFFE6E1E5)
internal val surfaceDark = Color(0xFF49454F) // Mapped from Spec 'Surface' Dark for Cards
internal val onSurfaceDark = Color(0xFFE6E1E5)
internal val surfaceVariantDark = Color(0xFF49454F)
internal val onSurfaceVariantDark = Color(0xFFCAC4D0)
internal val outlineDark = Color(0xFF938F99)
internal val outlineVariantDark = Color(0xFF49454F)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE6E1E5)
internal val inverseOnSurfaceDark = Color(0xFF313033)
internal val inversePrimaryDark = Color(0xFF6750A4)
internal val surfaceDimDark = Color(0xFF141316)
internal val surfaceBrightDark = Color(0xFF3B383E)
internal val surfaceContainerLowestDark = Color(0xFF0F0D10)
internal val surfaceContainerLowDark = Color(0xFF1D1B20)
internal val surfaceContainerDark = Color(0xFF211F26)
internal val surfaceContainerHighDark = Color(0xFF2B2930)
internal val surfaceContainerHighestDark = Color(0xFF36343B)

val lightScheme =
    lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

val darkScheme =
    darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
