disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length

opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - "*/.build/*"

analyzer_rules: # Rules run by the analyzer (requires strict mode)
  - unused_import

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
